# Generated by Django 4.1.7 on 2023-05-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='goods_unit',
            field=models.CharField(default='份', max_length=50),
        ),
    ]
